### ISSUE TITLE
Add libavif to render AVIF image

### ISSUE THREAD

**Issue by tats-u** [WebKitForWindows/WebKitRequirements#183]
Fixed by #168

https://caniuse.com/avif
https://github.com/microsoft/playwright/issues/22781
https://bugs.webkit.org/show_bug.cgi?id=261368

AVIF, the next generation image format, is supported by all modern browsers. However, WebKit for Windows has not supported it yet.
It's much more popular than JPEG XL (libjxl) and should be supported by WebKit for Windows as soon as possible.

https://bugs.webkit.org/show_bug.cgi?id=268503

libavif seems to be used to render AVIF image in WebKit.

AVIF image has been adopted by more and more websites day by day because it's much superior than lossy WebP and JPEG.

**Comment by donny-dont** [comment]
Hi @tats-u and anyone else who finds this particular issue.

This repository started back in early 2018 after we decided that `vcpkg` was a good path forward for managing third party dependencies of WebKit for Windows. When we started `vcpkg` was very young and didn't have a lot of the features it now has. If we started this project today using `vcpkg` we would approach things much differently and this repository would just have specific [overlays](https://learn.microsoft.com/en-us/vcpkg/concepts/overlay-ports) that we could not land in the mainline registry.

Adding an additional port here means that we need to maintain said port. The mainline registry has a port defined for [`libavif`](https://github.com/microsoft/vcpkg/tree/master/ports/libavif) and its dependencies. If someone wants `libavif` support in a Windows WebKit build we suggest that you build that port in the mainline registry of `vcpkg`. You would then take the contents of the `installed/<triplet>` directory and place it in `WebKitLibraries/win` of your local checkout of WebKit.

In the future this repository may move towards using the mainline `vcpkg` registry with some overlays and at that time distributing `libavif` would be revisited.

Again at this time build `libavif` and add it to `WebKitLibraries/win` and your WebKit build will build with the ability to view AVIF files.

**Comment by tats-u** [comment]
@donny-dont Then we should mention libavif in REAME.
It's as important as libwebp and libjxl today and worth mentioned.

**Comment by donny-dont** [comment]
@tats-u adding disclaimer in #187 how does that look to you?

**Comment by tats-u** [comment]
@donny-dont I'd like libavif to be raised as an example.

**Comment by tats-u** [comment]
I'd like README to raise the names of libraries that are as helpful as the existing ones at the last chapter.

**Comment by donny-dont** [comment]
@tats-u the repository isn't setup in a manner to help you build out `libavif` so I'm not going to add it to the port listing. As I noted I may rework it so it would use the registry support of `vcpkg` at which time it would get a listing.

Are you using the Windows WebKit port directly in a product or are you just a user of Playwright?

**Comment by tats-u** [comment]
> the repository isn't setup in a manner to help you build out libavif so I'm not going to add it to the port listing.

I mean #188. We don't have to mention how to build it here, but just the existence. The lack of AVIF display functionality is not good for general-purpose Web browsers today.

> Are you using the Windows WebKit port directly in a product or are you just a user of Playwright?

Latter, but I *would* include libavif if I developed a Webkit-based browser for Windows.

**Comment by donny-dont** [comment]
@tats-u the migration will be complete when https://github.com/WebKit/WebKit/pull/36366 lands.

So you would be able to build with avif support using the `--avif` flag in `build-webkit` and it will build `libavif` during the process.

**Comment by tats-u** [comment]
@donny-dont Thank you for the information. It would be better if `--no-avif` option would also exist (it can have no effects as of now but is reserved for the future when AVIF is opted out).
