### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by Erdroy** [WebKitForWindows/WebKitRequirements#54]
Hello,

I am currently in the process of porting WebKit onto another platform(s), and I would like to use and base off of these scripts.
But, I noticed that there is no license specified. Could you add one or say if it is ok, to maintain own internal fork?

Thank you,
Damian Korczowski

**Comment by donny-dont** [comment]
Hi @Erdroy the library is primarily build scripts to package all the libraries we use to build WebKit so we hadn't put any license on the repo itself.

Having said that when there is a CMake port that isn't present in the original repository there may be licenses attached from the place we found it. For example the ICU one comes with a LICENSE attached to the top.

**Comment by Erdroy** [comment]
Hi @donny-dont 

Basically, a repository without proper license means that it cannot be modified, redistributed or done anything useful with it. So that is why I opened this issue.
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license

**Comment by donny-dont** [comment]
Added a LICENSE.txt
